### PR TITLE
(ft):message when we don't have any search result

### PR DESCRIPTION
**Pull request by jackamrl**
My contribution consists of displaying a message when the search result is empty, indicating that no results match the search made.  

image

@shakiroye

### CODE REVIEW

**Comment by shakiroye** [comment]
That's great!
But the message should be in English.

Please keep the way the tags are.
And may be you should review your extension for formatting.

**Comment by jackamrl** [comment]
> That's great! But the message should be in English.
> 
> Please keep the way the tags are. And may be you should review your extension for formatting.

Okay. My bad; i will update the PR

**Comment by shakiroye** [comment]
> > That's great! But the message should be in English.
> > Please keep the way the tags are. And may be you should review your extension for formatting.
> 
> Okay. My bad; i will update the PR

Cool

**Comment by jackamrl** [comment]
I think it's okay now

**Review by shakiroye — APPROVED** [review]

**Comment by shakiroye** [comment]
Cool!
Thanks for the interest!

**Pull request merged**
